### ISSUE TITLE
https://searx.fidonet.io

### ISSUE THREAD

**Issue by joacimmelin** [searx/searx-instances#100]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [x] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [x] I do recognize that without a bot protection, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by unixfox** [comment]
Did you install an antibot solution or not? You checked both of the two last elements but you need to check only one.

**Comment by dalf** [comment]
I close this issue for now. Feel free to edit your initial message, add comment.
