### ISSUE TITLE
Add https://searx.bar

### ISSUE THREAD

**Issue by zevlee** [searx/searx-instances#101]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [x] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [ ] I do recognize that without a bot protection, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by dalf** [comment]
I think there is a typo in your settings.yml: 

It should be 
```yaml
result_proxy:
    url : https://searx.bar/morty
```

not
```yaml
result_proxy:
    url : https://https://searx.bar/morty
```

**Comment by zevlee** [comment]
Thank you for pointing it out. I fixed the error in the URL and it looks like morty is working fine now.
