### ISSUE TITLE
Configure https://searx.bar

### ISSUE THREAD

**Issue by zevlee** [searx/searx-instances#102]
Hello, I maintain https://searx.bar and it looks like there's [something](https://cryptcheck.fr/https/searx.bar) that's causing the HTTPS check to trip up when scanning it. As far as I'm aware, users are able to access my instance, and other websites like the ones listed below are able to scan it just fine. Is there something that I need to do to my configuration to allow the HTTPS check to work properly? The instance is installed with searx-docker on Ubuntu Minimal 20.04. It has only what I needed to get the instance running.

Results from other websites:
[Mozilla Observatory results](https://observatory.mozilla.org/analyze/searx.bar)
[SSL Labs results](https://www.ssllabs.com/ssltest/analyze?d=searx.bar)
[Security Headers results](https://securityheaders.com/?q=searx.bar&hide=on&followRedirects=on)

**Comment by dalf** [comment]
* cryptcheck doesn't support x25519
* since your instance only support x25519, cryptcheck can't connect to your instance
* see https://github.com/searx/searx-stats2/issues/58 for more details.

**Comment by zevlee** [comment]
I'm not sure if that's the issue. The identical configuration happens to work for a different instance of mine: https://search.zevlee.me.

[Cryptcheck results](https://cryptcheck.fr/https/search.zevlee.me)

Perhaps it has to do with the .bar TLD for whatever reason?

**Comment by zevlee** [comment]
I took the issue over to the cryptcheck repo, and [they were able to solve the problem](https://github.com/aeris/cryptcheck/issues/54). The website https://cryptcheck.fr is able to scan https://searx.bar fine now, so hopefully the version used for this repo will be able to as well.
