### ISSUE TITLE
Add https://searx.simonoener.com

### ISSUE THREAD

**Issue by nickia007** [searx/searx-instances#103]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [x] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [ ] I do recognize that without a bot protection, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by dalf** [comment]
I strongly encourage you to follow https://github.com/searx/searx-docker/blob/master/rules.json especially this part:
https://github.com/searx/searx-docker/blob/a7443cdc5f246fe85a63e9b9594bbb4f82e3b6e5/rules.json#L112-L123

**Comment by nickia007** [comment]
> I strongly encourage you to follow https://github.com/searx/searx-docker/blob/master/rules.json especially this part:
> https://github.com/searx/searx-docker/blob/a7443cdc5f246fe85a63e9b9594bbb4f82e3b6e5/rules.json#L112-L123

I've adoped my rules.json according to the recommended.

**Comment by dalf** [comment]
It seems whatever the user agent (curl, FF, Chrome), the `/search` path returns `Rate limit exceeded`.

**Comment by nickia007** [comment]
I am not sure about the commented out line.

```
    server_name searx.simonoener.com;

    location / {
        proxy_pass       http://127.0.0.1:4004/;
        proxy_set_header Host $http_host;
        proxy_set_header Connection $http_connection;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Scheme $scheme;
        #proxy_set_header X-Script-Name /searx;
    }

    location /static {
        alias /usr/local/searx/searx-src/searx/static;
    }

    location /morty {
        proxy_pass       http://127.0.0.1:3000/;
        proxy_set_header Host $http_host;
        proxy_set_header Connection $http_connection;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Scheme $scheme;
    }
```

**Comment by nickia007** [comment]
I've deleted [this part](https://github.com/searx/searx/blob/c2aaf6f99276022a7e268fdb4dc29ce33a774813/utils/templates/etc/filtron/rules.json#L66-L76), now it seems to be working.
