### ISSUE TITLE
Add https://searx.dynv6.net

### ISSUE THREAD

**Issue by TheFlipside** [searx/searx-instances#104]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [x] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [ ] I do recognize that without a bot protection, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by dalf** [comment]
It seems filtron is not installed ? or is misconfigured ?

* `curl https://searx.dynv6.net/search?q=test` is not blocked
* The JSON output is not blocked even after 5 tries

For reference : https://github.com/searx/searx-docker/blob/master/rules.json

**Comment by TheFlipside** [comment]
I think I managed to fix the issue

Seems I wasn't so sure about the nginx configuration so originally I had these blocks

```
location / {
    proxy_pass http://127.0.0.1:8888;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_cache_bypass $http_upgrade;
}

location /searx {
    proxy_pass         http://127.0.0.1:4004/;

    proxy_set_header   Host             $http_host;
    proxy_set_header   Connection       $http_connection;
    proxy_set_header   X-Real-IP        $remote_addr;
    proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
    proxy_set_header   X-Scheme         $scheme;
    proxy_set_header   X-Script-Name    /searx;
}

location /searx/static {
    alias /usr/local/searx/searx-src/searx/static;
}
```

But reading through other open issues with their sample nginx configuration I realized I made a mistake and changed it to this

```
location / {
    proxy_pass         http://127.0.0.1:4004/;

    proxy_set_header   Host             $http_host;
    proxy_set_header   Connection       $http_connection;
    proxy_set_header   X-Real-IP        $remote_addr;
    proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
    proxy_set_header   X-Scheme         $scheme;
    proxy_set_header   X-Script-Name    /searx;
}

location /static {
    alias /usr/local/searx/searx-src/searx/static;
}
```

and it seems to work now as intended

I just hope I set up the morty the correct way by having the following in the nginx config as well
```

location /morty {
    proxy_pass         http://127.0.0.1:3000/;

    proxy_set_header   Host             $http_host;
    proxy_set_header   Connection       $http_connection;
    proxy_set_header   X-Real-IP        $remote_addr;
    proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
    proxy_set_header   X-Scheme         $scheme;
}
```

**Comment by unixfox** [comment]
You are probably not using the correct filtron rules because I can still fetch the JSON part more than 4 times in a row: https://searx.dynv6.net/searx/search?category_general=1&q=ok&pageno=1&time_range=None&language=en-US&format=json

Please acknowledge if that's the case or if you want to have your instance added even if you don't have a proper antibot solution implemented.

**Comment by TheFlipside** [comment]
I give up on this, sorry to have wasted resources
