### ISSUE TITLE
Add searx.vxempire.xyz

### ISSUE THREAD

**Issue by qorg11** [searx/searx-instances#106]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [x] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [ ] I do recognize that without a bot protection, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

Update: I' have installed filtron
In case it matters. I also have a .onion and .i2p address for this instance: 
* <http://z34zvdnudiq5om7v547g42nr36l4ut7pek6bx7prn4emi5ncdgo6jhad.onion>
* <http://dqiy6jikcijk7itntbjhgtw7txjt75fsc7qsgbei4ajpf5ockt2a.b32.i2p>
I haven't installed filtron in those addresses because I don't think darknets need bot protection. (Please let me know if they need)

**Comment by unixfox** [comment]
You didn't check `I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).` so do you give this right? If so please check it in your initial comment.

**Comment by qorg11** [comment]
Oh, yes, i've edited it and checked

**Comment by dalf** [comment]
How did you installed filtron ?
Currently it seems it doesn't work at all.

**Comment by dalf** [comment]
I close this request: without filtron (or another bot filter) your instance will soon be ban from different engines, and it will disappointing for everyone.
