### ISSUE TITLE
Delete https://search.nebulacentre.net

### ISSUE THREAD

**Issue by nebulaw2081d** [searx/searx-instances#109]
- [x] I am the webmaster

The instance is getting overwhelmed with requests, leading to significantly less accurate results. Additionally, searx.space does not seem to be providing the correct information regarding the security of the website. Due to these two factors, I would like the instance removed.

**Comment by dalf** [comment]
Done.

FYI, the TLS score is E because of this header:
`Strict-Transport-Security: : max-age=31536000`

It should be something like 
`Strict-Transport-Security: max-age=31536000; includeSubDomains; preload` (without the double `:` ).
to actually have HSTS preload.
