### ISSUE TITLE
Edit searx.maxxblow.de

### ISSUE THREAD

**Issue by 0hlov3** [searx/searx-instances#110]
Since I moved my instance to a new server, it shows as offline, but it is still accessible normally. Could you take a look at why this does not go back online?

Thanks a lot. =)

**Comment by unixfox** [comment]
Probably a duplicate of https://github.com/searx/searx-stats2/issues/64

**Comment by dalf** [comment]
It seems your HTTPS server is not listening on the IPv6 address.

Try for example: `curl -6 -vvvvvv https://searx.maxxblow.de/`

**Comment by 0hlov3** [comment]
I messed up with ip6table rules, so it was my fault. Everything should run again. Thank you! =)
