### ISSUE TITLE
Add https://anon.sx/

### ISSUE THREAD

**Issue by jnnngs** [searx/searx-instances#114]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [ ] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [ ] I do recognize that without a bot protection, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by unixfox** [comment]
Do you have an anti bot solution installed or not? You picked both of the two last fields.

**Comment by jnnngs** [comment]
Sorry, not at the moment but im planning to over the weekend.

**Comment by unixfox** [comment]
Ok keep us updated when you deployed it because it's a big component for a public Searx instance unless you really want to run your Searx instance without one.

**Comment by jnnngs** [comment]
ok, will do buddy. I'll reply to this issue once done.

cheers :)

**Comment by jnnngs** [comment]
Okay, added nginx-ultimate-bad-bot-blocker

thanks buddy

**Comment by unixfox** [comment]
I'm not sure that it will do anything because the bots are specially crafted for Searx and nginx-ultimate-bad-bot-blocker is for blocking general bots.

That's why the Searx team built filtron which is designed for Searx in the first place: https://github.com/asciimoo/filtron/. I strongly suggest you to use it instead.

Also, your TLS/SSL configuration is not up-to-date for the today standards. You can see that on this website: https://cryptcheck.fr/https/anon.sx. You should adjust your NGINX configuration for that.

**Comment by jnnngs** [comment]
thanks for the great advice buddy. I'll drop CF and add filtron.

Hold fire until I sort thing out :)

thanks again.

**Comment by jnnngs** [comment]
Hi Buddy,

anon.sx is now using filtron with the TLS/SSL configuration fixed.

https://tls.imirhil.fr/https/anon.sx <--- A+

https://www.ssllabs.com/ssltest/analyze.html?d=anon.sx&hideResults=on <--- A+

although https://cryptcheck.fr/https/anon.sx is showing E, which I dont understand?

any advice with its E on https://cryptcheck.fr/https/anon.sx ?

thanks buddy!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by unixfox** [comment]
Paste your web server configuration, you may have some ciphers that need to be removed.

**Comment by jnnngs** [comment]
Thanks buddy...

--------------
options-ssl-nginx,conf
--------------

# This file contains important security parameters. If you modify this file
# manually, Certbot will be unable to automatically provide future security
# updates. Instead, Certbot will print and log an error message with a path to
# the up-to-date file that you will need to refer to when manually updating
# this file.

ssl_session_cache shared:le_nginx_SSL:10m;
ssl_session_timeout 1440m;
ssl_session_tickets off;

ssl_protocols TLSv1.2 TLSv1.3;
ssl_prefer_server_ciphers on;

ssl_ciphers AES256+EECDH:AES256+EDH:!aNULL;

ssl_stapling on;
ssl_stapling_verify on;

ssl_ecdh_curve secp384r1;

------------------------

cheers

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by unixfox** [comment]
I'm really not an expert in NGINX, but you may try those ciphers: `ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384`

That's the one I currently use for searx.be, and they work great. It's based on the ones from https://ssl-config.mozilla.org but without the insecure ones.

**Comment by jnnngs** [comment]
Thanks. I've added them and retested. CSP is now A+ as well.

https://tls.imirhil.fr/https/anon.sx <-- A+

https://cryptcheck.fr/https/anon.sx <-- E, must be a cach'ing issue although its been re-run. All other cryptcheck sites are reporting A+

https://securityheaders.com/?q=https%3A%2F%2Fanon.sx&followRedirects=on CSP A+

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by unixfox** [comment]
I tried on another domain and I still got an E: https://cryptcheck.fr/https/www.anon.sx
Your NGINX configuration is maybe not reload or restart. I don't really know.

**Comment by jnnngs** [comment]
Fixed: https://cryptcheck.fr/https/anon.sx

The issue is that this TLS checker seems to be slightly out of date as it see "DHE-RSA-AES.*" as weak. I removed these from the SSL options and it then gave A+.

Can we add https://anon.sx to the public instances now?

BTW, thanks for all your help.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
