### ISSUE TITLE
https://searx.divided-by-zero.eu

### ISSUE THREAD

**Issue by divided-by-zero** [searx/searx-instances#121]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [x] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [ ] I do recognize that without a bot protection, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by divided-by-zero** [comment]
Seems like i missed Pick one :-)

[ ] I do recognize that without a bot protection, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by dalf** [comment]
It seems your HTTP server doesn't listen on its IPv6 address.

**Comment by divided-by-zero** [comment]
Hi,
thanks for this reply.
Could you please elaborate on how you tested this? For me it looks fine. 
Either the URL is transformed as of HSTS or with clients ignoring HSTS a 308 redirect is performed:

curl -v -6 --head http://searx.divided-by-zero.eu
* Rebuilt URL to: http://searx.divided-by-zero.eu/
*   Trying 2a02:c205:1000:6686::10...
* TCP_NODELAY set
* Connected to searx.divided-by-zero.eu (2a02:c205:1000:6686::10) port 80 (#0)
> HEAD / HTTP/1.1
> Host: searx.divided-by-zero.eu
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 308 Permanent Redirect
HTTP/1.1 308 Permanent Redirect
< Connection: close
Connection: close
< Location: https://searx.divided-by-zero.eu/
Location: https://searx.divided-by-zero.eu/
< Server: Caddy
Server: Caddy
---------------------------------------------
 wget -v -6 http://searx.divided-by-zero.eu
URL transformed to HTTPS due to an HSTS policy
--2021-03-08 11:57:07--  https://searx.divided-by-zero.eu/
Resolving searx.divided-by-zero.eu (searx.divided-by-zero.eu)... 2a02:c205:1000:6686::10
Connecting to searx.divided-by-zero.eu (searx.divided-by-zero.eu)|2a02:c205:1000:6686::10|:443... connected.
HTTP request sent, awaiting response... 200 OK

**Comment by unixfox** [comment]
I just tested with the same commands as you and at first I wasn't able to reach your webserver on IPv6 but after 5 retries it worked. Seems odd.

**Comment by divided-by-zero** [comment]
For me it does not seem to be the case. Sounds for me like an IPv6 ND issue at data center side. Maybe I can convince them to route my entire IPv6 subnet to the link-local of my firewall.

**Comment by divided-by-zero** [comment]
The ipv6 network is now statically routed. Could you please check if the issue is gone?
