### ISSUE TITLE
Add https://searx.svdm.xyz

### ISSUE THREAD

**Issue by svdmsvdm** [searx/searx-instances#129]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [x] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [ ] I do recognize that without a bot protection, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by svdmsvdm** [comment]
I'm aware my my tls rating is considered insecure, I'll maybe fix that later but for now I'm fine with that

**Comment by unixfox** [comment]
Please bump this issue once you will have solved the TLS rating.
I'm also seeing 500 errors when browsing on your instance. This need to be also solved.

**Comment by unixfox** [comment]
Searx is not served anymore on this instance. Reopen if this is fixed.
