### ISSUE TITLE
Add https://xeek.com

### ISSUE THREAD

**Issue by xeekdev** [searx/searx-instances#136]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [x] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [ ] I do recognize that without a bot protection, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by unixfox** [comment]
You picked both of the last two items. Which one did you deploy: an antibot solution or no antibot solution?

**Comment by xeekdev** [comment]
filtron is enabled. I read the second box to mean "I understand that if I ever remove bot protection, I'll be flooded" - I missed the "Pick one" instruction. I understand now.

**Comment by dalf** [comment]
the title should https://xeek.com

* Optional: cryptcheck [grade E](https://cryptcheck.fr/https/searx.sk), it can be improved using https://ssl-config.mozilla.org/
* Optional: observatory.mozilla.org [grade C](https://observatory.mozilla.org/analyze/searx.sk?third-party=false). It can be improved using https://github.com/searx/searx-docker/blob/4ad61d64991d76a7d300b7b867771ffed9f224ca/Caddyfile#L83
* Filtron is ok.
