### ISSUE TITLE
Add https://searx.zackptg5.com

### ISSUE THREAD

**Issue by Zackptg5** [searx/searx-instances#138]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [x] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [ ] I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by dalf** [comment]
* there is a CSP issue with the images.
* Optional : cryptcheck [grade F](https://cryptcheck.fr/https/searx.zackptg5.com), can be improved using https://ssl-config.mozilla.org/

---
* https://observatory.mozilla.org/analyze/searx.zackptg5.com?third-party=false

**Comment by Zackptg5** [comment]
How do you suggest I change this with the searx-docker img? Looks like the caddyfile uses $SEARX_TLS

Which CSP issue? Only CSP issue I'm seeing is `Blocks inline styles by not allowing 'unsafe-inline' inside style-src`
which is default searx settings - same in other instances with A+ rating on searx.space

**Comment by Zackptg5** [comment]
@dalf I removed the unsafe-inline part of CSP, that was the default for searx so if I notice any weird bugs, I'll re-enable it

**Comment by dalf** [comment]
It seems TLS and HTTP headers are A+, so LGTM.

**Comment by Zackptg5** [comment]
Looks like cryptcheck is an A+ now. I didn't change anything there so maybe it just took a couple days to refresh since I redid the instance
