### ISSUE TITLE
Add https://searx.sk

### ISSUE THREAD

**Issue by lubosm** [searx/searx-instances#140]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [x] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [ ] I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by dalf** [comment]
* Optional: observatory.mozilla.org/ [grade C](https://observatory.mozilla.org/analyze/searx.sk?third-party=false) : there is no `Content Security Policy` header, see for example : https://github.com/searx/searx-docker/blob/4ad61d64991d76a7d300b7b867771ffed9f224ca/Caddyfile#L83
* Optional: Cryptcheck [grade C](https://cryptcheck.fr/https/searx.sk). It can be improved using https://ssl-config.mozilla.org/
