### ISSUE TITLE
Add https://s.zhaocloud.net

### ISSUE THREAD

**Issue by assimag** [searx/searx-instances#143]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [x] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [ ] I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by dalf** [comment]
LGTM:
- cryptcheck [grade A+](https://cryptcheck.fr/https/s.zhaocloud.net)
- observatory.mozilla.org [grade A+](https://observatory.mozilla.org/analyze/s.zhaocloud.net?third-party=false)
- filtron is configured
- no error 404
