### ISSUE TITLE
Add https://searx.7m.ee

### ISSUE THREAD

**Issue by cumpal** [searx/searx-instances#144]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [x] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection. (fail2ban)
* [ ] I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by unixfox** [comment]
Hello, fail2ban is not enough. You need a protection like filtron in order to correctly filter the bots.
If you don't want to install filtron I can still go ahead and add your instance anyway.

**Comment by cumpal** [comment]
> 
> 
> Hello, fail2ban is not enough. You need a protection like filtron in order to correctly filter the bots.
> If you don't want to install filtron I can still go ahead and add your instance anyway.

Hi, you can add it anyway, i will install filtron later on if i see too much malicious/bot traffic
