### ISSUE TITLE
Add https://search.trom.tf/

### ISSUE THREAD

**Issue by TROMsite** [searx/searx-instances#148]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [ ] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [x] I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by unixfox** [comment]
I've added your searx instance, but I advise you to:
- Improve your TLS security, see: https://cryptcheck.fr/https/search.trom.tf
- Improve your score on Mozilla observatory: https://observatory.mozilla.org/analyze/search.trom.tf

**Comment by TROMsite** [comment]
Thanks I'll look into these!
