### ISSUE TITLE
Add https://searx.xkek.net/

### ISSUE THREAD

**Issue by tacerus** [searx/searx-instances#150]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [x] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [ ] I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by unixfox** [comment]
Hello,

Your filtron rules are not optimal, I'm able to do an infinite amount of requests (more than 5 requests) on the JSON results: https://searx.xkek.net/searx/search?category_general=1&q=ok&pageno=1&time_range=None&language=en&format=json

You may use these filtron rules instead: https://github.com/searx/searx-docker/blob/master/rules.json

This is just an advice and if you don't want to follow it I can add your instance anyway.

**Comment by tacerus** [comment]
Hi @unixfox! Thanks for the input, I appreciate it! I actually had the example rules loaded, but I temporarily disabled a couple filters as I was trying to fix the deprecated Limnoria Searx bot for IRC. I will re-enable all the filter rules very soon, and it'd be no problem if you add it already - as you wish.
