### ISSUE TITLE
Add https://northboot.xyz

### ISSUE THREAD

**Issue by northboot** [searx/searx-instances#168]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [x] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [ ] I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by vojkovic** [comment]
@northboot I tried to reach you on matrix, but couldn't get through. Your instance looks to be blocking the uptime robot, please could you fix this so your instance isn't delisted?

https://uptime.searxng.org/history/northboot-xyz
https://github.com/searxng/searx-instances-uptime/issues/8241
