### ISSUE TITLE
Add https://www.searxzh.cn

### ISSUE THREAD

**Issue by Sp1ke47** [searx/searx-instances#171]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [ ] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [x] I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by unixfox** [comment]
Your TLS certificate is invalid, please fix it.

**Comment by unixfox** [comment]
Closing due to a lack of replies and the website not serving Searx.

**Comment by Sp1ke47** [comment]
Sorry, I've been busy with other things these days. But I also use my Searx instance often. It always works well.

> The URL is not serving searx but morty.

I cannot get it. Morty is supposed to work on `https://morty.searxzh.cn`. Once you open `https://www.searxzh.cn` a huge searX logo pops out to welcome you and everything a Searx site should have is there. Doesn’t that mean Searx is serving?

I don’t know how the test bots work. However, I’m sure that my instance works.

BTW, I haven’t blocked any bots in my Nginx WAF. So a desirable result should be gotten.

**Comment by unixfox** [comment]
Searxzh.cn seems to be serving Searx now, it didn't, at least last time I tried it.

I'll add your instance as soon as I've some free time.
