### ISSUE TITLE
Add https://searx.tk

### ISSUE THREAD

**Issue by alefvanoon** [searx/searx-instances#172]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [x] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [ ] I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by unixfox** [comment]
Hello,

Your filtron rules are not optimal, I'm able to do an infinite amount of requests (more than 5 requests) on the JSON results: https://Searx.tk/search?category_general=1&q=ok&pageno=1&time_range=None&language=en-US&format=json

You may use these filtron rules instead: https://github.com/searx/searx-docker/blob/master/rules.json

This is just an advice and if you don't want to follow it I can add your instance anyway.

**Comment by alefvanoon** [comment]
I'll play with cloduflare bot rules.
I don't like cloudflare but i need it.

**Comment by unixfox** [comment]
> I'll play with cloduflare bot rules.
> I don't like cloudflare but i need it.

You don't really need it, cloudflare is not a must-have. I've been hosting a popular Searx instance for almost 3 years, I don't use cloudflare and I never had any issue.

**Comment by alefvanoon** [comment]
> You don't really need it, cloudflare is not a must-have. I've been hosting a popular Searx instance for almost 3 years, I don't use cloudflare and I never had any issue.

Thank you for your suggestions.
But I can't think them now.

**Comment by alefvanoon** [comment]
Is there a problem?
Why this issues is not closed yet?

**Comment by unixfox** [comment]
> Is there a problem?
> Why this issues is not closed yet?

You haven't reply if you fixed the filtron rules or if you don't want to do it.

**Comment by alefvanoon** [comment]
> You haven't reply if you fixed the filtron rules or if you don't want to do it.

I don't want to do it please add my instance.
Thanks.

**Comment by unixfox** [comment]
Closing as your searx instance doesn't work, error: "SSL handshake failed".

Please reopen if you fixed the issue and I'll add your instance.

**Comment by alefvanoon** [comment]
Fixed...
