### ISSUE TITLE
Add https://searx.lamardebits.org

### ISSUE THREAD

**Issue by blackhold** [searx/searx-instances#174]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [x] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [x] I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by unixfox** [comment]
Hello,

Your filtron rules are not optimal, I'm able to do an infinite amount of requests (more than 5 requests) on the JSON results: https://searx.lamardebits.org/search?category_general=1&q=ok&pageno=1&time_range=None&language=en-US&format=json

You may use these filtron rules instead: https://github.com/searx/searx-docker/blob/master/rules.json

This is just an advice and if you don't want to follow it I can add your instance anyway.

**Comment by blackhold** [comment]
Hi! wait! I just installed searx, maybe I need to do some tunning! I'm looking for change the theme and install stats plugin that also it is still not working!

Thanks!

- Blackhold

**Comment by unixfox** [comment]
Sorry for the late reply, due to my limited free time you should ask for some help in the community of searx: https://github.com/searx/searx/discussions/categories/installation-issue-custom

I'm only here for adding new public Searx instances.

**Comment by unixfox** [comment]
Closing as your instance seems to return no results at all.

Reopen if you fixed the issue.

**Comment by blackhold** [comment]
Hello, could you check that now the limits are enabled? I putted filtron in the front.

I documented (in spanish) the install and the configuration, I wish it could be helpful! any comments are welcome :)

https://blackhold.nusepas.com/2022/01/11/searx-buscar-sin-ser-traceado/

Thanks!

**Comment by unixfox** [comment]
Still not working, I'm able to do an infinite amount of requests to https://searx.lamardebits.org/searx/search?category_general=1&q=ok&pageno=1&time_range=None&language=en-US&format=json

You need to avoid serving searx from the path /searx and this will fix the filtron rules.

**Comment by blackhold** [comment]
Don't really where to fix it, I have commented the line "proxy_set_header   X-Script-Name    /searx;" and don't allows to access.

Thanks for your help :)

**Comment by unixfox** [comment]
Nothing really changed, you need to stop serving searx from the path /searx but instead serve it from the root path (/).

**Comment by blackhold** [comment]
I'm asking about what configuration I have to do? thanks

**Comment by unixfox** [comment]
I'm unfortunately not familiar with the official setup of searx with NGINX.

Do note though that if you don't really know anything about NGINX and (linux in general) I don't recommend hosting a public searx instance because there are a lot of bad actors that will try to abuse your instance and you won't be able to stop them. This will thus decrease the usability/stability of your searx instance.

**Comment by blackhold** [comment]
ok, thanks. Then I only will offer to people close to me.
