### ISSUE TITLE
add https://vsrv15195.customer.xenway.de/searx

### ISSUE THREAD

**Issue by magotar** [searx/searx-instances#177]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [x] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [x] I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by unixfox** [comment]
You should either pick if you installed an anti bot solution or not. 

You picked both, please rectify on your initial comment.

**Comment by unixfox** [comment]
Closing due to a lack of replies and clarification about the bot protection.
