### ISSUE TITLE
Add https://searx.tiekoetter.com

### ISSUE THREAD

**Issue by tiekoetter** [searx/searx-instances#179]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [x] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [ ] I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by unixfox** [comment]
Hello,

Your filtron rules are not optimal, I'm able to do an infinite amount of requests (more than 5 requests) on the JSON results: https://searx.tiekoetter.com/searx/search?category_general=1&q=ok&pageno=1&time_range=None&language=en-US&format=json

You may use these filtron rules instead: https://github.com/searx/searx-docker/blob/master/rules.json

This is just an advice, if you don't want to apply it then feel free to reply here by confirming it, then I'll go ahead and add your instance to the public list.

**Comment by tiekoetter** [comment]
Ok but I have these rules unaltered from GitHub in place. So what should I do now?

**Comment by unixfox** [comment]
These rules don't work because you are running searx under the subdirectory `/searx`. You can either:
- Serve searx directly from the root path
- Adapt the rules so that they work for the subdirectory `/searx`.

**Comment by tiekoetter** [comment]
should be fixed now.
