### ISSUE TITLE
Add https://trovu.komun.org

### ISSUE THREAD

**Issue by alex-berbel** [searx/searx-instances#180]
* [X] It is my instance.
* [X] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [ ] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [X] I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by unixfox** [comment]
Hello,

Your filtron rules are not optimal, I'm able to do an infinite amount of requests (more than 5 requests) on the JSON results: https://trovu.komun.org/search?category_general=1&q=ok&pageno=1&time_range=None&language=es&format=json

You may use these filtron rules instead: https://github.com/searx/searx-docker/blob/master/rules.json

**Comment by unixfox** [comment]
Closing due to a lack of replies.

Please reopen after answering to my questions.
