### ISSUE TITLE
Add https://searx.hummel-web.at

### ISSUE THREAD

**Issue by diehummel** [searx/searx-instances#183]
* [X] It is my instance.
* [X] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [X] I have installed [filtron](https://github.com/asciimoo/filtron/)
* [ ] I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by tiekoetter** [comment]
I don't think you correctly configured filtron as there seems to be no rate limiting for json requests on your instance.

https://searx.hummel-web.at/searx/search?q=test&format=json

**Comment by diehummel** [comment]
The Rate limit is set to 2.
Refresh 3 times and you should see "Rate limit exceeded"
