### ISSUE TITLE
Add search.antonkling.se and z34ambyi6makk6ta7ksog2sljly2ctt2sa3apekb7wkllk72sxecdtad.onion

### ISSUE THREAD

**Issue by 0xc1f1** [searx/searx-instances#184]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [x] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [ ] I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by unixfox** [comment]
Hello,

Your filtron rules are not optimal, I'm able to do an infinite amount of requests (more than 5 requests) on the JSON results: https://search.antonkling.se/searx/search?category_general=1&q=ok&pageno=1&time_range=None&language=en-US&format=json

You may use these filtron rules instead: https://github.com/searx/searx-docker/blob/master/rules.json

This is just an advice and if you don't want to follow it I can add your instance anyway.

**Comment by 0xc1f1** [comment]
I have fixed this by applying the filtron rules you mentioned. You can add my now instance.

**Comment by unixfox** [comment]
Your TLS certificate is invalid.

**Comment by unixfox** [comment]
Added in https://github.com/searx/searx-instances/commit/28fe7db6d7b321bec95a0d6890aca819d63bd1e8
