### ISSUE TITLE
Add https://anonsearch.xyz

### ISSUE THREAD

**Issue by thiccpad** [searx/searx-instances#192]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

### Bot protection

Yes, I have installed filtron. I build a docker container from the official repo.

**Comment by thiccpad** [comment]
You're right. I think the problem is with my nginx configuration, as it didn't include filtron yet. I just thought, maybe I should build it from the ground up with Searxng when I have the time.

**Comment by unixfox** [comment]
Any update on filtron? Should I add your instance without a good bot protection anyway?

**Comment by unixfox** [comment]
Closing due to a lack of replies.
