### ISSUE TITLE
Add https://search.modalogi.com

### ISSUE THREAD

**Issue by georg-mayer** [searx/searx-instances#210]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

### Bot protection

Yes, I have installed filtron (other rules).

**Comment by unixfox** [comment]
Hello,

Your filtron rules are not optimal, I'm able to do an infinite amount of requests (more than 5 requests) on the JSON results: https://search.modalogi.com/searx/search?category_general=1&q=ok&pageno=1&time_range=None&language=fr&format=json

You may use these filtron rules instead: https://github.com/searx/searx-docker/blob/master/rules.json

This is just an advice and if you don't want to follow it I can add your instance anyway.

**Comment by georg-mayer** [comment]
Hello,

thanks a lot for the advice - I updated the filtron rules now with your suggestions. 

Would be great if you could add the site. Thanks for your help!

Cheers,
Georg

**Comment by unixfox** [comment]
Hi,

I'm still able to do an infinite amount of requests to the same URL that I sent on my previous command. I think you should stop serving searx on the /searx path and the rules will work fine.

**Comment by unixfox** [comment]
Closing due to a lack of replies.
