### ISSUE TITLE
Add https://sx.catgirl.cloud/

### ISSUE THREAD

**Issue by 999eagle** [searx/searx-instances#211]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

### Bot protection

Yes, I have installed filtron (rules.json from searx-docker).

**Comment by vojkovic** [comment]
Hi @999eagle 

Thanks for maintaining your instance so well over the years.

Can you please ensure that your instance remains up to date? Your instance seems to be using a version from two months ago, 2025-04-09. I kindly request you update to a version at the very least 1 week old. It may be easier to have a program that automatically updates SearXNG for you. Example programs for keeping up to date: watchtower, cron, ouroboros.

Cheers - let me know if you have any questions.

**Comment by 999eagle** [comment]
instance updated now, thanks for the reminder. https://github.com/NixOS/nixpkgs/pull/415838 has been opened for both the update and to add an update script to automate package updates in the future.

**Comment by unixfox** [comment]
I would advise to avoid using searx/searx-instances repo anymore. SearX is archived project.

catgirl is in the matrix room for searxng instances maintainers, you should ask the searxng team @vojkovic if you don't have access to it yet.

**Comment by vojkovic** [comment]
> I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Your bot detection (anubis) is blocking searx.space from accessing your instance. You must whitelist the check.searx.space server in your bot detection or disable it. @999eagle

**Comment by 999eagle** [comment]
sorry about that, the bot detection (iocaine actually, not anubis, but doesn't really matter) should be configured to whitelist the current ips of check.searx.space (i.e. `167.235.158.251` and `2a01:4f8:1c1c:8fc2::1`) now
