### ISSUE TITLE
Add http://searxbgetrkiwxhdwi6svpgh7eotopqyxhbqiokrwzg7dcte44t36kyd.onion/

### ISSUE THREAD

**Issue by alefvanoon** [searx/searx-instances#213]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

### Bot protection

No, I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by unixfox** [comment]
Is this instance related to https://searx.tk, like this one added in https://github.com/searx/searx-instances/issues/172?

**Comment by alefvanoon** [comment]
Nope...
