### ISSUE TITLE
Add https://serx.cf

### ISSUE THREAD

**Issue by inoblue** [searx/searx-instances#220]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

### Bot protection

Yes, I have installed filtron (rules.json from searx-docker).

### Source code URL

https://github.com/inoblue/searx

**Comment by inoblue** [comment]
BTW, when using rules from https://github.com/searx/searx-docker/blob/master/rules.json, I found that [this rule](https://github.com/searx/searx-docker/blob/276f88394a2ffd55d0ef5774619566d806016b94/rules.json#L73) will cause unexpected rate limit. The reason is that `Connection=close` header is only valid in http/1.0 and http/1.1, so when using http/2 in web server, this rule would be accidently triggered. The solution is to avoid usage of http/2 in web server.

**Comment by unixfox** [comment]
I've added your instance but do note that you are loading some analytics resources, so your instance will receive an E letter in the HTML column and may be ranked lower than the other instances.
