### ISSUE TITLE
Add https://swivro.net

### ISSUE THREAD

**Issue by kasperireland** [searx/searx-instances#221]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

### Bot protection

Yes, I have installed antibot-proxy or another bot protection.

### Source code URL

https://github.com/Swivro/searxng

### Comment

This instance also offers a Tor Hidden Service accessible via the following link: http://sdupg55ie7jpj3urdgyhxzgcv5ube7bq5gzbdtvpa3k44wdlxoeuvpid.onion/

The hidden service URL might change 1 or 2 times this year, and if it does, it will be updated on the site footer (swivro.net).

Lastly, though I have installed bot protection on my web server, it is currently disabled as I am waiting for a response from the provider (BotGuard) regarding an issue I am experiencing with their software.

**Comment by unixfox** [comment]
As per the AGPL license, you are required to disclose your source code: https://github.com/searx/searx/blob/master/LICENSE

**Comment by kasperireland** [comment]
> As per the AGPL license, you are required to disclose your source code if some modification were made: https://github.com/searx/searx/blob/master/LICENSE

The only modifications I made were to the Oscar template (modified some basic HTML and CSS), and those changes can be seen by viewing the webpage source. I have not touched anything else besides settings.yml
Am I still required to disclose my source code if it's identical? I feel like that would be kind of pointless, because as mentioned, I only modified some basic HTML and CSS on the Oscar template, and those changes can be seen by viewing the source of the webpage.

The license basically states that I must disclose my code when I distribute, publish or serve modified or derivative software. I'm not sure if I would consider modifying some HTML and CSS on the Oscar template to be modifying the source code. I do also see numerous other instances listed at searx.space which modified the HTML and CSS of the template in the same way that I did, and they also do not disclose their source, as the source code link in their footer just goes to the original searx repository.

**Comment by unixfox** [comment]
Just because some people aren't doing the right thing doesn't automatically mean you should do the same.

The oscar theme is part of the SearX source code, and you are publicly publishing (though https://swivro.net) a modified version of SearX so as per the license you have to disclose your source code.

**Comment by return42** [comment]
> I do not have a git repository for its code since it is identical, aside from what I just mentioned above.

I recommend to have one / I recommend to fork SearXNG (or searx) and commit your modifications on top .. to update from SearXNG (or searx) just rebase.  This is how I maintain my instance in a branch darmarit.org https://github.com/return42/searxng/commits/darmarit.org

**Comment by kasperireland** [comment]
Okay, I see. Can you give me until the end of the day to create a git repo
for my source code? Currently 3 AM and am heading to sleep.

**Comment by unixfox** [comment]
You have all the time you want, I'm just not adding your instance until the source code is provided in the first comment.

**Comment by kasperireland** [comment]
Will send a link to the repo shortly

**Comment by kasperireland** [comment]
I have updated the first comment

> You have all the time you want, I'm just not adding your instance until the source code is provided in the first comment.

**Comment by unixfox** [comment]
Thank you for publishing the source code.
Do note that if your onion URL changes, you will have to ask for editing the URL in the searx instances list here: https://github.com/searx/searx-instances/issues/new/choose
