### ISSUE TITLE
Add searx.lwhr.xyz

### ISSUE THREAD

**Issue by lukewhrit** [searx/searx-instances#75]
* [X] It is my instance.
* [X] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

**Comment by dalf** [comment]
filtron is installed, but it seems there is no restriction on the number of json request ?

Do you have something like this in rules.json: 
```
            {
                "name": "rss/json limit",
                "filters": [
                    "Param:format=(csv|json|rss)"
                ],
                "interval": 121,
                "limit": 2,
                "stop": true,
                "actions": [
                    { "name": "log"},
                    { "name": "block",
                      "params": {
                          "message": "Rate limit exceeded"
                      }
                    }
                ]
            },
```
from https://github.com/asciimoo/searx/blob/9f2446c44467d1ef6b85430996208bc2bdfa1b3a/utils/templates/etc/filtron/rules.json#L94-L110 ( ```"limit": 2,``` could be ```"limit": 0,```).

**Comment by lukewhrit** [comment]
Seems like I don't have any ratelimits for bots, I'll change that. This is my `rules.json` FYI: https://gist.github.com/lukewhrit/d5d9a1bec12c0ce7d00863c3ec527c19

**Comment by dalf** [comment]
I'm sorry for the long delay.

It seems the real URL is searx.lwhr.xyz/searx/

filtron 
* doesn't block these requests:
   * ```curl https://searx.lwhr.xyz/``` <-- ok
   * ```curl https://searx.lwhr.xyz/searx/``` <-- ok
   * ```curl https://searx.lwhr.xyz/searx/?q=1``` <-- problem
* blocks
   * ```curl https://searx.lwhr.xyz/?q=1```  <-- ??

Perhaps this line
https://gist.github.com/lukewhrit/d5d9a1bec12c0ce7d00863c3ec527c19#file-rules-json-L50
should be
```
"Path=^(/searx|/searx/search)$"
```

**Comment by lukewhrit** [comment]
Changing line 50 to `"Path=^(/searx|/searx/search)$"` doesn't seem to have done anything.

**Comment by unixfox** [comment]
@lukewhrit Did you manage to fix your filtron rules?

**Comment by lukewhrit** [comment]
> @lukewhrit Did you manage to fix your filtron rules?

No.

**Comment by unixfox** [comment]
> > @lukewhrit Did you manage to fix your filtron rules?
> 
> No.

Do you want to go ahead and add your instance anyway or do you want us to help you to fix the filtron rules?

**Comment by lukewhrit** [comment]
> Do you want to go ahead and add your instance anyway or do you want us to help you to fix the filtron rules?

Sure, try adding it. I think I may have just fixed filtron too.
