### ISSUE TITLE
Add https://tromland.org/searx/

### ISSUE THREAD

**Issue by tiotrom** [searx/searx-instances#85]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [x] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [x] I do recognize that without a bot protection, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by unixfox** [comment]
According to https://cryptcheck.fr/https/tromland.org, your server is accepting old TLS protocols which are very insecure. You can use https://ssl-config.mozilla.org/ to have some good examples on how to harden the TLS security of your web server.

This is not mandatory, just an advice but keep in mind that your instance won't appear on the top of the https://searx.space list if it is accepting old TLS protocols.

Just reply here if you managed to improve the security of your web server or if you don't want to change anything.

**Comment by tiotrom** [comment]
I am waiting for Alexio, the one who is in charge of our SearX instance, to comment on this. I am the project "manager" you could say, but he is the tech-guy ;). He is aware of this and he is looking into it.

**Comment by tiotrom** [comment]
So Alexio investigated this and here's what he told me:

" Changing our server TLS settings would prevent users with older operating systems and browsers to access our TROMland services. I would keep for now the current settings, with compatibility for older devices and browsers from the last 20 years. So, our SearX instance can be listed as it is for now, as out goal is to provide the trade-free services for anyone, using newer and older devices alike."

**Comment by unixfox** [comment]
It's understandable, even though it's quite strange to support devices that are 20 years old. I'm going to add your instance.

Again do note: your instance won't appear at the top of the list of https://searx.space because its TLS settings is considered bad for security in 2020.

**Comment by tiotrom** [comment]
Thank you and I get your point for sure. I will tell Alexio and if we change the TLS settings we will update it here.
