### ISSUE TITLE
Add https://searx.likkle.monster/

### ISSUE THREAD

**Issue by likklemore** [searx/searx-instances#86]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

**Comment by unixfox** [comment]
Did you install a bot protection like [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection?

**Comment by likklemore** [comment]
No, I'm using traefik as a reverse proxy.

**Comment by dalf** [comment]
Are you okay with this:
_I do recognize that without a bot protection, my instance will be flooded by bots and could have some of its engines stop working (an example is Google)._

?

**Comment by likklemore** [comment]
Yes.
