### ISSUE TITLE
Add https://searxzh.cn

### ISSUE THREAD

**Issue by Sp1ke47** [searx/searx-instances#87]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [x] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [ ] I do recognize that without a bot protection, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by dalf** [comment]
FYI:
* it seems filtron is not installed.
* optional: you can improve the TLS grade (currently F) using https://ssl-config.mozilla.org/
