### ISSUE TITLE
Add https://search.libremiami.org/

### ISSUE THREAD

**Issue by RobertoJBeltran** [searx/searx-instances#88]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [x] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [ ] I do recognize that without a bot protection, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

I think filtron is working, but would appreciate verification.

We're serving the modified source files, but there's also a [repo](https://gitlab.com/libremiami/libremiami-search)

**Comment by dalf** [comment]
FYI:
* It seems filtron is not installed ? (`curl https://.../?q=test` should return an HTTP error 429).
* you can improve the TLS grade (currently F) using https://ssl-config.mozilla.org/
* I see the version 0.16.0, but the google engine is working, so I guess it is a mix ? (just for my curiosity).
* In the source code ( 👍 ) , it is not simple to browse some directories: for example https://search.libremiami.org/full-source/searx/templates/legacy/ : 
   * It is possible to publish to either publish a .zip / .tar.gz file or git repository ?

**Comment by RobertoJBeltran** [comment]
Hey @dalf thanks so much for all your help. I think I might have filtron working now, and I bumped up the TLS grade, though I might still need to work on it. For any other newbies that might walk through here, in addition to the mozilla resource [I found this blog article helpful](https://libre-software.net/tls-nginx/) and I think these are [the criteria used](https://git.imirhil.fr/aeris/cryptcheck). It was fun getting acquainted with nginx. 

I'm honestly not 100 on the version, but I'm guessing we should probably upgrade soon.

I've removed the full-source path and just linked the repo instead then

**Comment by dalf** [comment]
* the TLS grade is A+ ✔️
* filtron:
     * ```curl ../?q=test``` doesn't work: good ✔️
     * Firefox, search for something, click multiple time on the "JSON" button at the bottom at the page: there is no blocking here. See https://github.com/searx/searx-docker/blob/7ad4d4903d0ce41de4094d5fe0fecda156b41eaa/rules.json#L112-L123

**Comment by unixfox** [comment]
@RobertoJBeltran Any news? Did you finish your filtron integration?

**Comment by dalf** [comment]
Filtron doesn't block the JSON output.

I close the issue, feel free to add comment / reopen.
