### ISSUE TITLE
Add https://searx.smlnd.xyz/

### ISSUE THREAD

**Issue by SJM1095** [searx/searx-instances#91]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [x] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [ ] I do recognize that without a bot protection, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by unixfox** [comment]
It seems like your instance don't have a good enough TLS security. You can see its rating here: https://cryptcheck.fr/https/searx.smlnd.xyz

Here is a NGINX example configuration in order to get A rating for the TLS security: https://ssl-config.mozilla.org/#server=nginx&version=1.17.7&config=modern&openssl=1.1.1d&guideline=5.6

**Comment by SJM1095** [comment]
I'll try and improve the TLS security in order to get an A+ rating before adding it to the instance list. I've removed the ciphers like you suggested and enabled TLSv1.3 only. After running cryptcheck it now displays an error saying TLS is not supported (it is, and it works). 

Once I've fixed these issues I'll let you know. In the mean time, could you confirm that filtron works correctly on my searx instance? I had some trouble setting it up initially and wanted to confirm that it does indeed work as intended.

**Comment by unixfox** [comment]
> I'll try and improve the TLS security in order to get an A+ rating before adding it to the instance list. I've removed the ciphers like you suggested and enabled TLSv1.3 only. After running cryptcheck it now displays an error saying TLS is not supported (it is, and it works).

Unfortunately cryptcheck doesn't support TLS 1.3 yet so that's why you get this error. Enable TLS 1.2 and it will work just fine. By the way enabling TLS 1.2 is perfectly fine because it's a protocol that is still considered secure as of now.

> Once I've fixed these issues I'll let you know. In the mean time, could you confirm that filtron works correctly on my searx instance? I had some trouble setting it up initially and wanted to confirm that it does indeed work as intended.

Filtron doesn't seem to be enabled at all. I'm able to do some search using curl on your Searx instance so that's not good.

**Comment by SJM1095** [comment]
> Unfortunately cryptcheck doesn't support TLS 1.3 yet so that's why you get this error. Enable TLS 1.2 and it will work just fine. By the way enabling TLS 1.2 is perfectly fine because it's a protocol that is still considered secure as of now.

Ive re-enabled TLSv1.2 as well as providing support for TLSv1.3. This should be fixed.

> Filtron doesn't seem to be enabled at all. I'm able to do some search using curl on your Searx instance so that's not good.

I followed the documentation @ https://searx.github.io/searx/ in order to install searx, filtron and morty. The filtron daemon seems to be running fine. I'll have a look into this issue and see if i can remedy it. Do you have any pointers on common configuration mistakes / things to look into? Otherwise I'll refer back to the documentation + google. 

Thanks for your feedback so far.

**Comment by unixfox** [comment]
> I followed the documentation @ [searx.github.io/searx](https://searx.github.io/searx/) in order to install searx, filtron and morty. The filtron daemon seems to be running fine. I'll have a look into this issue and see if i can remedy it. Do you have any pointers on common configuration mistakes / things to look into? Otherwise I'll refer back to the documentation + google.

Unfortunately I can't really help you about that, I don't have the same setup as you.
Maybe @dalf could help you about that.

**Comment by dalf** [comment]
What is the output of `systemctl status filtron`  and `journalctl -u fitrlon` ?

**Comment by SJM1095** [comment]
> What is the output of systemctl status filtron

filtron.service - filtron
   Loaded: loaded (/lib/systemd/system/filtron.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-10-26 15:06:04 UTC; 58min ago
 Main PID: 121792 (filtron)
    Tasks: 5 (limit: 1117)
   Memory: 6.9M
   CGroup: /system.slice/filtron.service
           └─121792 /usr/local/filtron/go-apps/bin/filtron -api 127.0.0.1:4005 -listen 127.0.0.1:4004 -rules /etc/filtron/rules.json -target 127.0.0.1:8888

>  and journalctl -u filtron ?

Oct 26 15:06:04 localhost systemd[1]: Started filtron.
Oct 26 15:06:04 localhost filtron[121792]: 2020/10/26 15:06:04 9 rules loaded from /etc/filtron/rules.json
Oct 26 15:06:04 localhost filtron[121792]: 2020/10/26 15:06:04 API listens on 127.0.0.1:4005
Oct 26 15:06:04 localhost filtron[121792]: 2020/10/26 15:06:04 Proxy listens on 127.0.0.1:4004
Oct 26 15:06:08 localhost filtron[121792]: [roboagent limit] 2020-10-26 15:06:08.720  HEAD 127.0.0.1:4004/ "" "curl/7.64.0"
Oct 26 15:06:17 localhost filtron[121792]: [roboagent limit] 2020-10-26 15:06:17.817  HEAD 127.0.0.1:4004/ "" "curl/7.64.0"
Oct 26 15:09:05 localhost filtron[121792]: [roboagent limit] 2020-10-26 15:09:05.394  HEAD 127.0.0.1:4004/ "" "curl/7.64.0"
Oct 26 15:12:59 localhost filtron[121792]: [roboagent limit] 2020-10-26 15:12:59.585  GET 127.0.0.1:4004/ "" "curl/7.64.0"
Oct 26 15:13:05 localhost filtron[121792]: [roboagent limit] 2020-10-26 15:13:05.944  GET 127.0.0.1:4004/?q=foo "" "curl/7.64.0
Oct 26 15:15:49 localhost filtron[121792]: [roboagent limit] 2020-10-26 15:15:49.366  HEAD 127.0.0.1:4004/ "" "curl/7.64.0"
Oct 26 15:24:20 localhost filtron[121792]: [roboagent limit] 2020-10-26 15:24:20.184  GET 127.0.0.1:4004/ "" "curl/7.64.0"
Oct 26 15:28:53 localhost filtron[121792]: [roboagent limit] 2020-10-26 15:28:53.078  HEAD 127.0.0.1:4004/ "" "curl/7.64.0"

I've posted the output of both commands above. I don't know if it's worth mentioning, but my searx instance @ https://searx.smlnd.xyz/ only works if I include the following in my server block:

location / {
include uwsgi_params;
uwsgi_pass unix:/run/uwsgi/app/searx/socket;
}

If i remove this then the page @ https://searx.smlnd.xyz/ displays a 404 error. However, I assume it has something to do with the errors received when I inspect the filtron service. Here is the output of the command "./filtron.sh inspect service"

service status & log
====================

sourced .config.sh :

  PUBLIC_URL          : https://searx.smlnd.xyz/
  PUBLIC_HOST         : 217.160.65.72
  FILTRON_URL_PATH    : /
  FILTRON_API         : 127.0.0.1:4005
  FILTRON_LISTEN      : 127.0.0.1:4004
  FILTRON_TARGET      : 127.0.0.1:8888

INFO:  service account filtron available.
INFO:  ~filtron: go is installed
INFO:  ~filtron: filtron app is installed
INFO:  got 404 from http://127.0.0.1:4005
ERROR: API not available at: http://127.0.0.1:4005
INFO:  got 429 from http://127.0.0.1:4004
INFO:  got 200 from http://127.0.0.1:8888
INFO:  Filtron's target is available at: http://127.0.0.1:8888
INFO:  got 200 from https://searx.smlnd.xyz/
INFO:  public URL   --> https://searx.smlnd.xyz/
INFO:  internal URL --> http://127.0.0.1:4004

My apologies for the extra information, but something tells me the fix to my problem is something simple that I've overlooked due to my lack of knowledge - It's the first time I've hosted a website.

**Comment by dalf** [comment]
I guess this is the problem :
```nginx
location / {
include uwsgi_params;
uwsgi_pass unix:/run/uwsgi/app/searx/socket;
}
```

you don't need this since the intended workflow is : 
`[nginx] --[http]--> [filtron] --[http]--> [searx]`

@return42  can you have a look ?

**Comment by SJM1095** [comment]
Finally got around to making some fixes (or so I hope). I removed the following from my server block

> location / {
include uwsgi_params;
uwsgi_pass unix:/run/uwsgi/app/searx/socket;
}

Usually this would result in my searx page giving a 404 error. However, after changing further information in the server block this seems to have stopped.

Could you run some tests to determine if filtron is now working on my instance? I issued a curl command to my searx instance and I now receive a "Rate limit exceeded" message. Whereas before I was given full information from the page. 

With that being said, when inspecting the filtron service via utils, I still receive the following:
>ERROR: API not available at http://127.0.0.1:4005

**Comment by dalf** [comment]
Sorry for the delay.

With the JSON format, there is no limit on the number of request.

As a reference:
https://github.com/searx/searx-docker/blob/7ad4d4903d0ce41de4094d5fe0fecda156b41eaa/rules.json#L112-L123

**Comment by SJM1095** [comment]
Thanks for the reply, I'll check it out.

In the meantime could you provide me with the tools/utilities you are using to test filtron functionality so that I can run them myself after making changes to my instance. Would save me from making comments on this issue each time I _think_ it is working as intended.

**Comment by dalf** [comment]
For now, It's a set of different manual tests:
* `curl <instance>`: should not work.
* with a browser, send a request: should work.
* click on the JSON button, refresh 5 times: the 5th requests should be blocked (according to the configuration on searx-docker).

**Comment by unixfox** [comment]
@SJM1095 Any news?

**Comment by SJM1095** [comment]
@unixfox I've exhausted every modification and change to my config i can think of. I've looked at every issue submitted to the instance list and I've read the documentation countless times. I cannot get filtron working whatsoever. 

Searx works fine and morty works fine. However, the filtron API stills shows as unavailable . I've even gone so far to uninstall searx, morty and filtron and do a clean install. However, the problem still persists.

**Comment by unixfox** [comment]
Maybe something else is listening on the port 4005 but even if the API is not available or doesn't work that shouldn't keep filtron from working. When using curl for doing a search on your instance it returns me `Rate limit exceeded` so that's a good sign because this means filtron is working.

Your filtron rules are just not complete enough, use these rules: https://github.com/searx/searx-docker/blob/master/rules.json. You should not be able to fetch the JSON/RSS too frequently, here is a URL example: https://searx.smlnd.xyz/searx/?category_general=1&q=ok&pageno=1&time_range=None&language=en-US&format=json.

After you have replaced this file, reply here and I'll look again at your instance.

**Comment by SJM1095** [comment]
I replaced the rules.json file then deactivated + activated filtron once again alongside a fresh restart of nginx. Once I applied the new rules I no longer receive the "rate limit exceeded" message and instead get the full page information. 

I'm not sure if this is because they are the rules under the docker branch or not (although I don't see why this would matter at all). 

Additionally, I assumed it was because I hadn't changed the following code 
`"name": "searx.space",
"filters": ["Header:X-Forwarded-For=nslookup(check.searx.space)"],
"stop": true,
"actions": [{ "name": "log"}]`

I replaced "searx.space" with "searx.smlnd.xyz". However, upon doing so I received an error when trying to reach my searx instance.

Either way, after changing the files filtron appears to not work at all as opposed to half working in my original case.

**Comment by unixfox** [comment]
Could you paste your NGINX configuration? You shouldn't be running Searx in a subpath that's not normal.

> I'm not sure if this is because they are the rules under the docker branch or not (although I don't see why this would matter at all).

Not that's unrelated, these rules works for all setup.

> Additionally, I assumed it was because I hadn't changed the following code
> `"name": "searx.space", "filters": ["Header:X-Forwarded-For=nslookup(check.searx.space)"], "stop": true, "actions": [{ "name": "log"}]`
> 
> I replaced "searx.space" with "searx.smlnd.xyz". However, upon doing so I received an error when trying to reach my searx instance.

No need to replace that, it's for whitelisting searx.space.

**Comment by SJM1095** [comment]
Here is my searx config located at /etc/nginx/sites-enabled/

server{
	server_name searx.smlnd.xyz;


	location / {
    	proxy_pass         http://127.0.0.1:4004/;

    	proxy_set_header   Host             $http_host;
    	proxy_set_header   Connection       $http_connection;
    	proxy_set_header   X-Real-IP        $remote_addr;
    	proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
    	proxy_set_header   X-Scheme         $scheme;
    	proxy_set_header   X-Script-Name    /searx;
	}	
	
	location /static {
	alias /usr/local/searx/searx-src/searx/static;
	}

	location /morty {
   	proxy_pass         http://127.0.0.1:3000/;

    	proxy_set_header   Host             $http_host;
    	proxy_set_header   Connection       $http_connection;
    	proxy_set_header   X-Real-IP        $remote_addr;
    	proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
    	proxy_set_header   X-Scheme         $scheme;
	}

    listen 443 ssl http2; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/aboutme.smlnd.xyz/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/aboutme.smlnd.xyz/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
 
    # HSTS (ngx_http_headers_module is required) (63072000 seconds)
    add_header Strict-Transport-Security "max-age=63072000" always;

    # OCSP stapling
    ssl_stapling on;
    ssl_stapling_verify on;

}


server{
    if ($host = searx.smlnd.xyz) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


	
	listen 80;
	server_name searx.smlnd.xyz;
    return 404; # managed by Certbot


}

**Comment by unixfox** [comment]
I'm very sorry but I just don't find any advice to give to you about that. Maybe @return42, the one that wrote the installation script, could help you for your issue.

By the way, if you don't mind using Docker, you may try searx-docker: https://github.com/searx/searx-docker it includes every needed filtron rules and allows to easily update Searx to the latest version.

**Comment by return42** [comment]
> Maybe @return42, the one that wrote the installation script, could help you for your issue.

I will do so, but ATM I am slow-witted / for me its not clear what you mean with:

>  I do understand now, it's the installation script that does, that's odd to that. I don't know why @return42 did that... That breaks filtron rules.

Do you like to add a issue at https://github.com/searx/searx/issues we can process on / thanks!

**Comment by cavemanr** [comment]
I've tried to install and run searx on an Ubuntu 20.04 LTS and have the same problem with the filtron API.

Are there any updates on this problem?

The next thing I will try is to install searx on an Ubuntu 18.04. LTS to check out if the problem exists there too.

**Comment by unixfox** [comment]
> I've tried to install and run searx on an Ubuntu 20.04 LTS and have the same problem with the filtron API.
> 
> Are there any updates on this problem?
> 
> The next thing I will try is to install searx on an Ubuntu 18.04. LTS to check out if the problem exists there too. 

Please open a github discussion instead, this is not an issue tracker for issues in Searx: https://github.com/searx/searx/discussions/categories/installation-issue-official-wiki

**Comment by SJM1095** [comment]
> 
> 
> I've tried to install and run searx on an Ubuntu 20.04 LTS and have the same problem with the filtron API.
> 
> Are there any updates on this problem?
> 
> The next thing I will try is to install searx on an Ubuntu 18.04. LTS to check out if the problem exists there too.

Hi there, I've since given up on trying to make filtron and the likes work as intended. If i recall correctly, the reason there is installation problems regarding this is due to an error in the code. This is why there are little to no issues setting up searx using "mywebsite.com/searx" whereas there are a lot of problems setting it up in the form of a subdomain such as "searx.mywebsite.com". 

I'll go ahead and close this issue and refer to the wiki to see if anyone has come up with a solution in the past few months.
