### ISSUE TITLE
Add https://searx.guillaumea.fr

### ISSUE THREAD

**Issue by guiand888** [searx/searx-instances#93]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [x] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [ ] I do recognize that without a bot protection, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by guiand888** [comment]
I made a number of changes to nginx and certbot to improve the SSL score. Not sure how to refresh results from cryptcheck.fr though.

**Comment by unixfox** [comment]
filtron seems to be installed but you should try to improve the TLS configuration of your webserver, it's an E grade according to cryptcheck: https://cryptcheck.fr/https/searx.guillaumea.fr.

You can look at a correct TLS configuration on this website if you need help about that: https://ssl-config.mozilla.org/#server=nginx&version=1.17.7&config=modern&openssl=1.1.1d&guideline=5.6

Let me know if you did some changes then I can look again at your TLS configuration or tell me if you don't want to make some changes then I can add your instance right away.

**Comment by guiand888** [comment]
I fixed the TLS configuration. Let me know if everything seems good now.   

On a side note, it seems the advanced configuration suggested by Mozilla restricts protocols to TLSv1.3 and that this protocol doesn't work with cryptcheck.fr. I get a message that says `Error during analysis: TLS seems not supported on this server`.   

I originally had a configuration very close to the Mozilla Intermediate config, with HSTS, stappling, etc. I simply removed any cipher with a Diffie–Hellman key exchange from the config and it should be A+ now. Seems a bit of a drastic jump though :sweat_smile:

**Comment by guiand888** [comment]
Just one more question: do I need to take any proactive step to allow searx.space to check my instance? I only have the default filtron config in place.
Thanks!

**Comment by unixfox** [comment]
> On a side note, it seems the advanced configuration suggested by Mozilla restricts protocols to TLSv1.3 and that this protocol doesn't work with cryptcheck.fr. I get a message that says `Error during analysis: TLS seems not supported on this server`.
> 
> I originally had a configuration very close to the Mozilla Intermediate config, with HSTS, stappling, etc. I simply removed any cipher with a Diffie–Hellman key exchange from the config and it should be A+ now. Seems a bit of a drastic jump though sweat_smile

I forgot to tell you about TLS1.3, just let TLS 1.2 enabled, that's fine.

> Just one more question: do I need to take any proactive step to allow searx.space to check my instance? I only have the default filtron config in place.
> Thanks!

Here are the recommended filtron rules: https://github.com/searx/searx-docker/blob/master/rules.json. At the second line you can find a filtron rules used to whitelist searx.space.

**Comment by guiand888** [comment]
> Here are the recommended filtron rules: https://github.com/searx/searx-docker/blob/master/rules.json. At the second line you can find a filtron rules used to whitelist searx.space.

Thanks! Everything should be set now.

**Comment by dalf** [comment]
* in your searx/settings.yml, I think `result_proxy.url` is set to a local IP (may be it was set by a script), it should be `https://searx.guillaumea.fr/morty`.
* searx.space shows `HTTP status code 429` : it seems [this rule](https://github.com/searx/searx-docker/blob/a7443cdc5f246fe85a63e9b9594bbb4f82e3b6e5/rules.json#L2-L7) is not activated:
```yaml
    {
        "name": "searx.space",
        "filters": ["Header:X-Forwarded-For=nslookup(check.searx.space)"],
        "stop": true,
        "actions": [{ "name": "log"}]
    },
```
