### ISSUE TITLE
Add https://hmsearx.h0meserver.com

### ISSUE THREAD

**Issue by actionhenkt** [searx/searx-instances#94]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [x] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [x] I do recognize that without a bot protection, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by unixfox** [comment]
Perfect job! Filtron and a correct TLS configuration are implemented. Just lack of IPv6, but we can't force everyone to implement it.

**Comment by actionhenkt** [comment]
ah that was pretty quick, thanks!
