### ISSUE TITLE
Add https://searx.bbaovanc.com

### ISSUE THREAD

**Issue by BBaoVanC** [searx/searx-instances#97]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [x] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [ ] I do recognize that without a bot protection, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by dalf** [comment]
Added.

I strongly encourage you to follow https://github.com/searx/searx-docker/blob/master/rules.json especially this part:
https://github.com/searx/searx-docker/blob/a7443cdc5f246fe85a63e9b9594bbb4f82e3b6e5/rules.json#L112-L123

**Comment by BBaoVanC** [comment]
Ok, just added those. Looks like I had an older set of rules. Although I
had to remove the section which blocks the header `Connection=close` or
else it blocks me searching through the search bar on Firefox.
